# Generated by Django 4.1.13 on 2024-05-08 13:33

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genero',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('gen_nombre', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='peliculas',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('pel_codigo', models.CharField(max_length=10, unique=True)),
                ('pel_titulo', models.CharField(max_length=80)),
                ('pel_protagonista', models.CharField(max_length=80)),
                ('pel_duracion', models.IntegerField()),
                ('pel_sinopsis', models.CharField(max_length=2000)),
                ('pel_foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('pel_genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appPeliculas.genero')),
            ],
        ),
    ]
